services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    restart: always
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    restart: always
    build: ./mongodb
    image: mongo
    ports:
      - '27017:27017'